const fs = require("fs");
const os = require("os");
const path = require("path");
const pkgPath = path.join(__dirname, "..", "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const parts = pkg.version.split("-")[0].split(".").map(Number);
parts[2]++;
pkg.version = parts.join(".");
const output = JSON.stringify(pkg, null, 2) + os.EOL;
fs.writeFileSync(pkgPath, output, "utf8");
console.log(pkg.version);
