// GENERATED by bin/build-route-manifest.js — do not edit by hand.
/* eslint-disable */
// @ts-nocheck — its app/api imports vanish while api is stashed during the export build.
import * as r0 from "../app/api/agent/[id]/bash-output/route";
import * as r1 from "../app/api/agent/[id]/events/route";
import * as r2 from "../app/api/agent/[id]/route";
import * as r3 from "../app/api/agent/new/route";
import * as r4 from "../app/api/agent/running/events/route";
import * as r5 from "../app/api/auth/all-providers/route";
import * as r6 from "../app/api/auth/api-key/[provider]/route";
import * as r7 from "../app/api/auth/login/[provider]/route";
import * as r8 from "../app/api/auth/logout/[provider]/route";
import * as r9 from "../app/api/auth/providers/route";
import * as r10 from "../app/api/cwd/browse/route";
import * as r11 from "../app/api/cwd/validate/route";
import * as r12 from "../app/api/default-cwd/route";
import * as r13 from "../app/api/file-index/route";
import * as r14 from "../app/api/files/[...path]/route";
import * as r15 from "../app/api/git/diff/route";
import * as r16 from "../app/api/git/status/route";
import * as r17 from "../app/api/home/route";
import * as r18 from "../app/api/models-config/check/route";
import * as r19 from "../app/api/models-config/route";
import * as r20 from "../app/api/models/route";
import * as r21 from "../app/api/modes/route";
import * as r22 from "../app/api/plugins/route";
import * as r23 from "../app/api/sessions/[id]/auto-name/route";
import * as r24 from "../app/api/sessions/[id]/context-usage/route";
import * as r25 from "../app/api/sessions/[id]/context/route";
import * as r26 from "../app/api/sessions/[id]/entries/[entryId]/thinking/route";
import * as r27 from "../app/api/sessions/[id]/export/route";
import * as r28 from "../app/api/sessions/[id]/route";
import * as r29 from "../app/api/sessions/[id]/state/route";
import * as r30 from "../app/api/sessions/route";
import * as r31 from "../app/api/skills/check/route";
import * as r32 from "../app/api/skills/install/route";
import * as r33 from "../app/api/skills/route";
import * as r34 from "../app/api/skills/search/route";
import * as r35 from "../app/api/skills/update/route";
import * as r36 from "../app/api/worktrees/route";

export interface RouteEntry { pattern: string; module: Record<string, unknown> }
export const routes: RouteEntry[] = [
  { pattern: "/api/agent/[id]/bash-output", module: r0 as Record<string, unknown> },
  { pattern: "/api/agent/[id]/events", module: r1 as Record<string, unknown> },
  { pattern: "/api/agent/[id]", module: r2 as Record<string, unknown> },
  { pattern: "/api/agent/new", module: r3 as Record<string, unknown> },
  { pattern: "/api/agent/running/events", module: r4 as Record<string, unknown> },
  { pattern: "/api/auth/all-providers", module: r5 as Record<string, unknown> },
  { pattern: "/api/auth/api-key/[provider]", module: r6 as Record<string, unknown> },
  { pattern: "/api/auth/login/[provider]", module: r7 as Record<string, unknown> },
  { pattern: "/api/auth/logout/[provider]", module: r8 as Record<string, unknown> },
  { pattern: "/api/auth/providers", module: r9 as Record<string, unknown> },
  { pattern: "/api/cwd/browse", module: r10 as Record<string, unknown> },
  { pattern: "/api/cwd/validate", module: r11 as Record<string, unknown> },
  { pattern: "/api/default-cwd", module: r12 as Record<string, unknown> },
  { pattern: "/api/file-index", module: r13 as Record<string, unknown> },
  { pattern: "/api/files/[...path]", module: r14 as Record<string, unknown> },
  { pattern: "/api/git/diff", module: r15 as Record<string, unknown> },
  { pattern: "/api/git/status", module: r16 as Record<string, unknown> },
  { pattern: "/api/home", module: r17 as Record<string, unknown> },
  { pattern: "/api/models-config/check", module: r18 as Record<string, unknown> },
  { pattern: "/api/models-config", module: r19 as Record<string, unknown> },
  { pattern: "/api/models", module: r20 as Record<string, unknown> },
  { pattern: "/api/modes", module: r21 as Record<string, unknown> },
  { pattern: "/api/plugins", module: r22 as Record<string, unknown> },
  { pattern: "/api/sessions/[id]/auto-name", module: r23 as Record<string, unknown> },
  { pattern: "/api/sessions/[id]/context-usage", module: r24 as Record<string, unknown> },
  { pattern: "/api/sessions/[id]/context", module: r25 as Record<string, unknown> },
  { pattern: "/api/sessions/[id]/entries/[entryId]/thinking", module: r26 as Record<string, unknown> },
  { pattern: "/api/sessions/[id]/export", module: r27 as Record<string, unknown> },
  { pattern: "/api/sessions/[id]", module: r28 as Record<string, unknown> },
  { pattern: "/api/sessions/[id]/state", module: r29 as Record<string, unknown> },
  { pattern: "/api/sessions", module: r30 as Record<string, unknown> },
  { pattern: "/api/skills/check", module: r31 as Record<string, unknown> },
  { pattern: "/api/skills/install", module: r32 as Record<string, unknown> },
  { pattern: "/api/skills", module: r33 as Record<string, unknown> },
  { pattern: "/api/skills/search", module: r34 as Record<string, unknown> },
  { pattern: "/api/skills/update", module: r35 as Record<string, unknown> },
  { pattern: "/api/worktrees", module: r36 as Record<string, unknown> },
];
